apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-server
spec:
  selector:
    matchLabels:
      app: ims-server-app
  template:
    metadata:
      labels:
        app: ims-server-app
    spec:
      containers:
        - image: aaarti/ims-server
          name: server
          ports:
            - containerPort: 8000